### ISSUE TITLE
Exception in setInterval callback - relating to SimpleSchema and/or Collection2

### ISSUE THREAD

**Issue by sunny-g** [sunny-g/whuffie#18]
Occurs every 10 minutes while server is running idle:
```
I20150628-20:51:30.067(-7)? Exception in setInterval callback: Error: When the modifier option is true, validation object must have at least one operator
I20150628-20:51:30.068(-7)?     at checkModifier (packages/aldeed:simple-schema/simple-schema-validation.js:271:1)
I20150628-20:51:30.068(-7)?     at doValidation1 (packages/aldeed:simple-schema/simple-schema-validation.js:321:1)
I20150628-20:51:30.068(-7)?     at doValidation (packages/aldeed:simple-schema/simple-schema-context.js:9:1)
I20150628-20:51:30.068(-7)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed:simple-schema/simple-schema-context.js:44:1)
I20150628-20:51:30.068(-7)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:317:1)
I20150628-20:51:30.068(-7)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)
I20150628-20:51:30.068(-7)?     at Accounts._expireTokens (packages/accounts-base/accounts_server.js:858:1)
I20150628-20:51:30.068(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150628-20:51:30.068(-7)?     at packages/meteor/timers.js:6:1
I20150628-20:51:30.068(-7)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by kaizvn** [comment]
add `blackbox: true` options inside `{type : Object}` to fix it.
Ie : `Schemakey : { type : Object, blackbox : true}` 
you can find the cause by read about `blackbox` of SimpleSchema.
